# Generated by Django 3.2.5 on 2021-11-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='bookn',
        ),
    ]
